<?php

namespace Notabenedev\ProductImport\Models;

use App\ImportYml;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;


class YmlFile extends Model
{
    use  HasFactory;

    protected $fillable = [
        "import_yml_id",
        "path",
        "type",
        "original_name"
    ];

    protected static function boot()
    {
        parent::boot();

    }

    /**
     *
     * Триггеры на удаление файлов
     */
    protected static function booting()
    {
        parent::booting(); // TODO: Change the autogenerated stub
        self::deleting(function(self $model){
            Storage::disk("public")->delete($model->path);
        });
    }

    public function yml()
    {
        return $this->belongsTo(ImportYml::class);
    }

    /**
     * Изменить дату создания.
     *
     * @param $value
     * @return string
     */
    public function getCreatedAtAttribute($value)
    {
        return datehelper()->changeTz($value);
    }
}
